POST http://localhost:4000/authors
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNjE2MDYsImV4cCI6MTY5MTE0ODAwNn0.eNIMR1Ca8WDkkSbhJ90bpHAo9SUPL23s7EgV8wm4_Us
Content-Type: application/json

{
    "name": "Abdulo"
}

###
GET http://localhost:4000/authors
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNjE2MDYsImV4cCI6MTY5MTE0ODAwNn0.eNIMR1Ca8WDkkSbhJ90bpHAo9SUPL23s7EgV8wm4_Us

###
GET http://localhost:4000/authors/64c5dafb455ed8ce4b7894a9
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNjE2MDYsImV4cCI6MTY5MTE0ODAwNn0.eNIMR1Ca8WDkkSbhJ90bpHAo9SUPL23s7EgV8wm4_Us

###
PATCH http://localhost:4000/authors/64c5dafb455ed8ce4b7894a9
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNjE2MDYsImV4cCI6MTY5MTE0ODAwNn0.eNIMR1Ca8WDkkSbhJ90bpHAo9SUPL23s7EgV8wm4_Us
Content-Type: application/json

{
    "name": "Abdullohhh"
}

###
DELETE  http://localhost:4000/authors/64c5dafb455ed8ce4b7894a9
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNjE2MDYsImV4cCI6MTY5MTE0ODAwNn0.eNIMR1Ca8WDkkSbhJ90bpHAo9SUPL23s7EgV8wm4_Us
