POST http://localhost:4000/books
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNDY0MjAsImV4cCI6MTY5MTEzMjgyMH0.HquT9qz_f19X3eh4c7aaeqnLPcTpR9JgkEky37KgyWw
Content-Type: application/json

{
    "title": "sss",
    "publisher": "64c560bc02c4eb054e420aac",
    "author": "64c5dafb455ed8ce4b7894a9",
    "copies": 2
}

###
GET http://localhost:4000/books
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNDY0MjAsImV4cCI6MTY5MTEzMjgyMH0.HquT9qz_f19X3eh4c7aaeqnLPcTpR9JgkEky37KgyWw

###
GET http://localhost:4000/books/64c5e6aeb6c5bfd43ce874ce
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNDY0MjAsImV4cCI6MTY5MTEzMjgyMH0.HquT9qz_f19X3eh4c7aaeqnLPcTpR9JgkEky37KgyWw


###
PATCH http://localhost:4000/books/64c5e6aeb6c5bfd43ce874ce
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNDY0MjAsImV4cCI6MTY5MTEzMjgyMH0.HquT9qz_f19X3eh4c7aaeqnLPcTpR9JgkEky37KgyWw
Content-Type: application/json

{
    "title": "js lerane",
    "publisher": "64c560bc02c4eb054e420aac",
    "author": "64c5dafb455ed8ce4b7894a9",
    "copies": 1
}

###
DELETE  http://localhost:4000/books/64c5f9ee012808c677afa046
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNDY0MjAsImV4cCI6MTY5MTEzMjgyMH0.HquT9qz_f19X3eh4c7aaeqnLPcTpR9JgkEky37KgyWw