POST http://localhost:4000/loans
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTA2OTYwMzksImV4cCI6MTY5MDc4MjQzOX0.mO06Qb_Qu88pw15F6fVccJLVhxlySl6o4mrkJxZAVgI
Content-Type: application/json

{
    "book": "64c5e6aeb6c5bfd43ce874ce",
    "out_date": "2023-07-30",
    "borrower": "64c54fcccb7bccdb8db42859"
}

###
GET http://localhost:4000/loans
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTA2OTYwMzksImV4cCI6MTY5MDc4MjQzOX0.mO06Qb_Qu88pw15F6fVccJLVhxlySl6o4mrkJxZAVgI
###
GET http://localhost:4000/loans/64c5f6a4684d5606b4d4ec4e
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTA2OTYwMzksImV4cCI6MTY5MDc4MjQzOX0.mO06Qb_Qu88pw15F6fVccJLVhxlySl6o4mrkJxZAVgI