POST http://localhost:4000/publishers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNDY0MjAsImV4cCI6MTY5MTEzMjgyMH0.HquT9qz_f19X3eh4c7aaeqnLPcTpR9JgkEky37KgyWw
Content-Type: application/json

{
    "name": "Abdulojh",
    "address": "nazarbe",
    "phone": "135545"
}

###
GET  http://localhost:4000/publishers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNDY0MjAsImV4cCI6MTY5MTEzMjgyMH0.HquT9qz_f19X3eh4c7aaeqnLPcTpR9JgkEky37KgyWw

###
GET http://localhost:4000/publishers/64c5fa85012808c677afa06c
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNDY0MjAsImV4cCI6MTY5MTEzMjgyMH0.HquT9qz_f19X3eh4c7aaeqnLPcTpR9JgkEky37KgyWw

###
PATCH  http://localhost:4000/publishers/64cba8012e97296029ee5b49
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNDY0MjAsImV4cCI6MTY5MTEzMjgyMH0.HquT9qz_f19X3eh4c7aaeqnLPcTpR9JgkEky37KgyWw
Content-Type: application/json

{
    "name": "Abdullohh1",
    "address": "nazarbee",
    "phone": "13554"
}

###
DELETE  http://localhost:4000/publishers/64cba8012e97296029ee5b49
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjRjNGVkYTk4NDE0MDY2Y2NiMmFkNWY2IiwiaXNTdXBlckFkbWluIjp0cnVlLCJpYXQiOjE2OTEwNDY0MjAsImV4cCI6MTY5MTEzMjgyMH0.HquT9qz_f19X3eh4c7aaeqnLPcTpR9JgkEky37KgyWw
